### ISSUE TITLE
Make a template for guide creation

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/admin#20]
### Overview
We need to have a template for creating new guides on the Admin team so that we can speed up the process and bring on more team members.

### Action Items
- [x] Review current method used during creation of 1Password guides and make a template from that
- [x] Make clear to make separate guides for processes and sub processes.
- [x] Decide what labels are needed and add them to the repo
- [x] Talk to Karen about it

### Resources/Instructions

[Epic for Workflow Modeling](https://github.com/hackforla/admin/issues/new?assignees=&labels=0.1-Status%3A+Setup+Epic&template=epic-for-workflow-modeling.md&title=Workflow+Modeling%3A+%5Bname+of+technology%5D)

[Guide Template](https://github.com/hackforla/admin/issues/new?assignees=&labels=0.2-Status%3A+Make+Appt&template=guide-template.md&title=Guide%3A+%5BTool%5D+%3A+%5BWorkflow%5D+)

#### Labels
Draft Guide 
Create Guide 
Needs Peer Review
Leadership Review 
Ready for publication
Published 
Published to admin only

**Comment by ExperimentsInHonesty** [comment]
# Potential text for Epic issue

Title: Workflow Modeling: [name of technology]

### Overview
We need to model the workflows of [name technology] so that we can create guide making issues.

### Action Items
- [ ] Record reviewing the application with the Subject Matter Expert (SME) to determine all features we are using and might use.
- [ ] 

### Resources

**Comment by kcoronel** [comment]
For epic issue:  hyperlink to label tracker

**Comment by ExperimentsInHonesty** [comment]
- [x] we need to go through all the issues that have already been made and make sure they have the correct labels and that the named epics label is the right color.
