### ISSUE TITLE
Create a Workflow Guide/Template:  1Password: Creating a New Vault

### ISSUE THREAD

**Issue by kcoronel** [hackforla/admin#27]
### Dependency
Creation of epic hackforla/knowledgebase-content#132 

### Action Items
- [x] Make appointment with member of admin team who is currently performing function.
    - [x] remove label: "Status: Make Appt" add label: "Status: Record"
- [x] Link folder for recording and guide in defined sections below (see Resources).
   - [x] Record workflow demo 
   - [x]  remove label: "Status: Record" add label: "Status: Upload"
- [x] Upload recording and transcript.
   - [x] link to folder, recording and transcript in the resources below
   - [x] remove recording and transcripts from local or cloud storage
      - [x] remove label: "Status: Upload" and add label: "Status: Create "As-Is"
- [x] Make a guide
   - [ ] Turn video transcript into step-by-step process confirmation
     - [x] remove label: "Status: Create "As-Is" add label: "Status: Review "As-Is""
- [x] Admin reviews the "As-Is" adding missing steps or notes
   - [x] remove label: "Status: Review "As-Is"" add label: "Status: Draft Guide"
- [ ] Make a Guide using guide template
     - [ ] remove label: "Status: Draft Guide" and label: "Status: Review Guide"
- [ ] Test guide with member of Admin team

### Resources
- Admin team member currently performing function: Bonnie Wolfe 

#### How to make a guide
- [Template for creating guides - WIP](https://docs.google.com/document/d/1-8gmeC-wnfM8C8fVvmTP1BLA2WfNjKH_XJrHB1OAV6Q/edit)
- [UI/UX for Guides](https://github.com/hackforla/knowledgebase-content/issues/93)

#### Folders
- Recordings & Transcripts
   - [Recordings general folder](https://drive.google.com/drive/folders/1dmX5df5TXm8F209O4-_BRmuW0NIcT-Ss)
   - Creating a new vault 
       - [📁](https://drive.google.com/drive/folders/1rntP262WODrqhQdOKcIfjvNwsGadqj9O?usp=sharing)
       - [⏺️](https://drive.google.com/file/d/1Zybs1lGrQEkPXStZblz6PzIxTv5FUCaT/view?usp=sharing) 
       - [✏️](https://drive.google.com/file/d/1RqFgXSBdcsOk0CdHbiUt72gFxvGJ2ofa/view?usp=sharing)

- Guides
  - [Guides general folder](https://drive.google.com/drive/folders/13aT7T3HblNidcwm2CMy7LQg-mAULL3Q7)
  - Create a New Vault on 1Password
       -  [📁](https://drive.google.com/drive/folders/1oufXHRhXnGK9O7bDBXRmwsvcfe93aGAn?usp=sharing)
       - [🎉](https://docs.google.com/document/d/1iPOYKHhUrN2giXNLdIt_gWi_jCUZbM1-WyXtDCel4jA/edit?usp=sharing) 
 
#### Legend
📁 = Folder
✏️= Transcription
⏺️ = Recording
📝 = Writeup 
🎉= Guide

#### Location of draft guide.
- Epic Issue https://github.com/hackforla/admin/issues/21
- [CREATE A NEW VAULT ON 1PASSWORD](https://docs.google.com/document/d/1iPOYKHhUrN2giXNLdIt_gWi_jCUZbM1-WyXtDCel4jA/edit?usp=sharing)

**Comment by ExperimentsInHonesty** [comment]
@kcoronel Left some notes for you in the guide.  I have changed the label back to draft guide.

**Comment by kcoronel** [comment]
I am working on this guide. I will post a comment and move it to Review/Questions when ready.

**Comment by camille-kay** [comment]
Commented on document. Main takeaways: Step 6 and its alternative are separated and worded in a (personally) confusing way; some formatting changes are suggested.

**Comment by kcoronel** [comment]
@camkan reviewed your changes. This document is ready to be re-reviewed.
