### ISSUE TITLE
Create a Workflow Guide/Template: 1Password: Add a Logo to 1Password Vault

### ISSUE THREAD

**Issue by kcoronel** [hackforla/admin#28]
### Dependency
Creation of epic hackforla/knowledgebase-content#132 

### Action Items
- [x] Make appointment with member of admin team who is currently performing function.
    - [x] remove label: "Status: Make Appt" add label: "Status: Record"
- [x] Link folder for recording and guide in defined sections below (see Resources).
   - [x] Record workflow demo 
   - [x]  remove label: "Status: Record" add label: "Status: Upload"
- [x] Upload recording and transcript.
   - [x] link to folder, recording and transcript in the resources below
   - [x] remove recording and transcripts from local or cloud storage
      - [x] remove label: "Status: Upload" and add label: "Status: Create "As-Is"
- [x] Make a guide
   - [x] Turn video transcript into step-by-step process confirmation
     - [x] remove label: "Status: Create "As-Is" add label: "Status: Review "As-Is""
- [x] Admin reviews the "As-Is" adding missing steps or notes
   - [x] remove label: "Status: Review "As-Is"" add label: "Status: Draft Guide"
- [x] Make a Guide using guide template
     - [x] remove label: "Status: Draft Guide" and label: "Status: Review Guide"
- [ ] Test guide with member of Admin team

### Resources
- Admin team member currently performing function: Bonnie Wolfe 

#### How to make a guide
- [Template for creating guides - WIP](https://docs.google.com/document/d/1-8gmeC-wnfM8C8fVvmTP1BLA2WfNjKH_XJrHB1OAV6Q/edit)
- [UI/UX for Guides](https://github.com/hackforla/knowledgebase-content/issues/93)

#### Folders
- Recordings & Transcripts
   - [Recordings general folder](https://drive.google.com/drive/folders/1dmX5df5TXm8F209O4-_BRmuW0NIcT-Ss)
   - Add Logo
       - [📁](https://drive.google.com/drive/folders/1REQ93mPJEUudnLJ7mh2bDvP5_-tZBrtv?usp=sharing)
       - [⏺️](https://drive.google.com/file/d/1xwbLLsAbdGyhP9-2WOfKFt1UTogNYFMx/view?usp=sharing) 
       - [✏️](https://docs.google.com/document/d/1NbMVzIDVN94E0eyyKc1r7dxru9Oey7hzz42v5jv_erI/edit?usp=sharing)

- Guides
  - [Guides general folder](https://drive.google.com/drive/folders/13aT7T3HblNidcwm2CMy7LQg-mAULL3Q7)
  - Add a Logo to 1Password Vault
       -  [📁](https://drive.google.com/drive/folders/1BFuHarEVKKydaXmnwKPh93MrHqMfT5l8?usp=sharing)
       - [🎉](https://docs.google.com/document/d/1Mg8jAcjJK83xO9c3g0VvB6B5RjpIzPB0W7W8Ozl4qkE/edit?usp=sharing) 
 
#### Legend
📁 = Folder
✏️= Transcription
⏺️ = Recording
📝 = Writeup 
🎉= Guide

#### Location of draft guide.
- Epic Issue hackforla/knowledgebase-content#132 
- [Guide: Add a Logo to 1Password Vault](https://docs.google.com/document/d/1Mg8jAcjJK83xO9c3g0VvB6B5RjpIzPB0W7W8Ozl4qkE/edit)

**Comment by ExperimentsInHonesty** [comment]
The steps work. We just need to make the language changes we talked about

**Comment by kcoronel** [comment]
Replace "Follow the steps listed below" with "use the steps that follow"

**Comment by camille-kay** [comment]
Comments on the latter part of the document added. Includes: removing option 1 image and using option 2 instead; and changing the total number of pages from 8 to 7 if deleting the option 1 image brings the page count down (which it may not).

**Comment by kcoronel** [comment]
@camkan thank you for your help! Resolved all of your comments.
