### ISSUE TITLE
Create a Workflow Guide/Template: 1Password: Recover Team Members 1Password Account in Case of Lockout or Forgotten Password

### ISSUE THREAD

**Issue by kcoronel** [hackforla/admin#29]
### Dependency
- [ ] Creation of epic https://github.com/hackforla/admin/issues/21

### Action Items
- [x] Make appointment with member of admin team who is currently performing function.
    - [x] remove label: "Status: Make Appt" add label: "Status: Record"
- [x] Link folder for recording and guide in defined sections below (see Resources).
   - [x] Record workflow demo 
   - [x]  remove label: "Status: Record" add label: "Status: Upload"
- [x] Upload recording and transcript.
   - [x] link to folder, recording and transcript in the resources below
   - [x] remove recording and transcripts from local or cloud storage
      - [x] remove label: "Status: Upload" and add label: "Status: Create "As-Is"
- [x] Make a guide
   - [x] Turn video transcript into step-by-step process confirmation
     - [x] remove label: "Status: Create "As-Is" add label: "Status: Review "As-Is""
- [x] Admin reviews the "As-Is" adding missing steps or notes
   - [x] remove label: "Status: Review "As-Is"" add label: "Status: Draft Guide"
- [x] Make a Guide using guide template
     - [x] remove label: "Status: Draft Guide" and label: "Status: Review Guide"
- [x] Test guide with member of Admin team

### Resources
- Admin team member currently performing function: Bonnie Wolfe 

#### How to make a guide
- [Template for creating guides - WIP](https://docs.google.com/document/d/1-8gmeC-wnfM8C8fVvmTP1BLA2WfNjKH_XJrHB1OAV6Q/edit)
- [UI/UX for Guides](https://github.com/hackforla/knowledgebase-content/issues/93)

#### Folders
- Recordings & Transcripts
   - [Recordings general folder](https://drive.google.com/drive/folders/1dmX5df5TXm8F209O4-_BRmuW0NIcT-Ss)
   - Recover Team Members 1Password Account in Case of Lockout or Forgotten Password
       - [📁](https://drive.google.com/drive/folders/19lNkdIJM7YNYM5Fom2LHcdiyeRH1lNax?usp=sharing)
       - Step 1 [⏺️](https://drive.google.com/drive/folders/1VPijcsyKpTtL1a9HqFIRfpNeCksX9dI3?usp=sharing) 
       - Step 2 [⏺️](https://drive.google.com/drive/folders/1CeVIzGOoJTcpb_CtvagWxZ8JgIxfI8fX?usp=sharing) 
       - Step 1 [✏️](https://drive.google.com/file/d/1F5-yTUy1ZOi4grJyS8RqdIjY1ggt0jTD/view?usp=sharing)
       - Step 2 [✏️](https://drive.google.com/file/d/1fdZwn4KCR9zgAUisJt2p-dqZQcDJnVTI/view?usp=sharing)
       
- Guides
  - [Guides general folder](https://drive.google.com/drive/folders/13aT7T3HblNidcwm2CMy7LQg-mAULL3Q7)
  - Guide: Removing Team Members from a 1Password Vault1Password Vault
       -  [📁](https://drive.google.com/drive/folders/1yGtK33AOCKbg4WetfwELzJRqzCgwJyc1?usp=sharing)
       - [🎉](https://docs.google.com/document/d/1TK7Y0tLsoeouhH-0fOgmPE2t5WjVD3VrRFSwitZJlhk/edit?usp=sharing) 
 
#### Legend
📁 = Folder
✏️= Transcription
⏺️ = Recording
📝 = Writeup 
🎉= Guide

#### Location of draft guide.
- Epic Issue https://github.com/hackforla/admin/issues/21
- [Guide: Recover Team Members 1Password Account](https://docs.google.com/document/d/1TK7Y0tLsoeouhH-0fOgmPE2t5WjVD3VrRFSwitZJlhk/edit#heading=h.c8tc614ce3iu)

**Comment by ExperimentsInHonesty** [comment]
The steps work. The guide just need to the languages changes we talked about.

**Comment by kcoronel** [comment]
This guide needs to be updated with a new method for removing folks - ask Bonnie if this requires a separate guide or should the step be added to this existing guide? Also, would we need a new video recording?

**Comment by kcoronel** [comment]
Should we edit this sentence "Follow the steps listed below"

**Comment by kcoronel** [comment]
Replace "Follow the steps listed below" with "use the steps that follow"

**Comment by kcoronel** [comment]
@ExperimentsInHonesty ready for review with Camille :)

**Comment by camkan** [comment]
Looks good.

**Comment by camille-kay** [comment]
@kcoronel @ExperimentsInHonesty - Can someone update the link in the description? It currently goes to the 'Guide: Removing Team Members from a 1Password Vault' instead of the 'Recover' document.
