### ISSUE TITLE
Workflow Modeling: Google Sites

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/admin#35]
### Overview
We need to model the workflows of Google Sites so that we can create guide making issues.

### Action Items
- [ ] Setup Items
  - [ ] Check to see if there is a label for the epic, and if not create a label for [name of technology] (e.g., 1password, GithHub, Google Drive)
  - [ ] Create folder for guides
  - [ ] Create folder for recordings
- [ ] Setup complete
   - [ ] remove label: "Status: Setup Epic" add label "Status: Make Appt"
- [ ] Make appointment with member of admin team who is currently performing function (see resources).
  - [ ] remove label: "Status: Make Appt" add label "Status: Recording Tool Overview"
- [ ] Record reviewing the application with member of admin team who is currently performing function to determine all features we are using and might use.
   - [ ] remove label: "Recording Tool Overview" add label "Status: Upload Overview"
- [ ] Upload recording and transcripts to its folder.
   - [ ] remove label: Status: Upload Overview" and add label "Status: Identify Workflows
- [ ] create a list of workflows that will not need guides at this time and define the reason why (decision record).
- [ ] create a list of all workflows that will need guides. 
- [ ] create folders inside the guides and recordings folders for each workflow
   - [ ] remove label: "Status: Identify workflows - Admin" and add label: "Status: Create Issues from Epic"
   - [ ] create issues for each workflow (using the guides creation template).
     - [ ] remove label: "Status: Create Issues from Epic" add  label: "Status: Monitor Epic" and move to _Start Here_ column
- [ ] ~Add this epics label to the tracker.~ - on hold for now

### Resources
- Admin team member currently performing function: 

- [Guide Creation Issue template]

#### Folders
- Recordings & Transcripts
   - 📁[Recordings general folder](https://drive.google.com/drive/folders/1dmX5df5TXm8F209O4-_BRmuW0NIcT-Ss)
   - 📁[INSERT NAME OF THE FOLDER YOU WILL CREATE]
   - Link to specific recording and transcript (add links to the emojis)
      - ⏺️
      - ✏️
- Guides
  - 📁[Guides general folder](https://drive.google.com/drive/folders/13aT7T3HblNidcwm2CMy7LQg-mAULL3Q7)
    - 📁[INSERT NAME AND LINK OF THE FOLDER YOU WILL CREATE]

#### Legend
📁 = Folder
✏️= Transcription
⏺️ = Recording
📝 = "As-Is":  Transcript edited down to steps (no pictures, no focus on writing instructions for others)
👷‍♀️ = Draft Guide Take the write up, put it in the Guide template and screen shots (or notes that screen shots are needed) and start working on the language.
🎉= Completed Guide

#### Workflows that need guides now
-

#### Workflows that don't need guides now
- Name of Workflow: 
  - Decision Record:
