### ISSUE TITLE
Create a Guide: Create a wiki for your project

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/admin#36]
### Overview

We need to create a guide that shows how to use the Hack for LA GitHub template wiki to create a new wiki for your project's GitHub repository so that each project team can create a wiki for the project. 

### Action Items

- [ ] Gather examples of how other Hack for LA projects have done, adding each example as a link in the resources section
   - [ ] Once done, remove the "TG: Gather Examples" label and add the "TG: Draft Template" label
- [ ] Create a draft template, either in markdown format in this issue or a google doc in the [product management google drive](https://drive.google.com/drive/folders/1lO8k_0Z1UejkuRlNMYlUl2xlqgyBmvrF?usp=sharing)
    - [ ] Once done, remove the "TG: Draft Template" label and add the "TG: Create Guide" label
- [ ] Create a guide on how to use the template 
   - [ ] Once done, remove the "TG: Create Guide" label and add the "TG: Review Guide" label
- [ ] Review the guide with product management communities of practice
   - [ ] Once done, remove the "TG: Review Guide" label and add the "TG: Leadership Review" label
- [ ] Present to Hack for LA leadership team for sign off
   - [ ] Once approved, remove the "TG: Leadership Review" label and add the "TG: Place Guide" label
- [ ] Possibly create an issue template on .github 
   - [ ] Include link to template under resources if you add it as a template in .github

### Resources
- Refer to hackforla/product-management#123 for how to write a guide and the guide template
- Update issue hackforla/product-management#128 with the name of item you are working
[Hack for LA's default repo wiki](https://github.com/hackforla/.github/wiki)

### To-do list
   - [x] Test it and indicate in the comments what is not working
   - [x] rewrite
   - [ ] test again, repeat as necessary until working
 - [ ] Add instructions to guide
    - Copy the wiki from the default repo 
    - Customize the wiki for your project

**Examples of good wikis**
[Design Systems](https://github.com/hackforla/design-systems/wiki)
[Civic Tech Index wiki](https://github.com/civictechindex/CTI-website-frontend/wiki)
[100 Automations wiki](https://github.com/100Automations/Website/wiki)
