### ISSUE TITLE
Add Members to Admin Team 

### ISSUE THREAD

**Issue by kcoronel** [hackforla/admin#39]
### Overview
We need to add more people doing workflow modeling and reviewing so that we can have end to end guides for all admin practices. 

### Action Items
- [ ] Check to see if there is an open roles board 
- [ ] If not, create an open roles board 
- [ ] Create an issue for recruiting each role type 
   - [ ] Draft roles 
   - [ ] Post roles on board 
   - [ ] Message on Slack
- [ ] Add Admin to Community of Practice website - HackforLA.org

### Resources/Instructions
[Community of Practice](https://www.hackforla.org/communities-of-practice)
[Admin FAQ](https://docs.google.com/document/d/1vgLsPrGY_P6UlJeaoBw47Om2drmzqH0BT1XmRruIcUk/edit)
[Recruitment Messaging](https://docs.google.com/document/d/1YgWQq4-Mp-olReyEyDQKPTsHNbKOPevErVIS0PmIyLg/edit)
