### ISSUE TITLE
Create a Workflow Guide/Template: 1Password: Add Owners to the 1Password Account

### ISSUE THREAD

**Issue by kcoronel** [hackforla/admin#40]
### Dependency
Creation of epic hackforla/knowledgebase-content#132 

### Action Items
- [x] Add this issue to the following Projects (right side of this issue)
   - [x] Repository: Task Board
   - [x] Organization: Guide Tracker
- [x] Make appointment with member of admin team who is currently performing function.
   - [x] remove label: "Status: Make Appt" add label: "Status: Record"
- [ ] Link folder for recording and guide in defined sections below (see Resources).
   - [ ] Record workflow demo 
     - [ ] remove label: "Status: Record" add label: "Status: Upload"
- [ ] Upload recording and transcript.
   - [ ] link to folder, recording and transcript in the resources below
   - [ ] remove recording and transcripts from local or cloud storage
      - [ ] remove label: "Status: Upload" and add label: "Status: Create "As-Is"
- [ ] Make a guide
   - [ ] Turn video transcript into step-by-step process confirmation
     - [ ] remove label: "Status: Create "As-Is" add label: "Status: Review "As-Is""
- [ ] Admin reviews the "As-Is" adding missing steps or notes
   - [ ] remove label: "Status: Review "As-Is"" add label: "Status: Draft Guide"
- [ ] Make a Guide using guide template
   - [ ] remove label: "Status: Draft Guide" and label: "Status: Review Guide"
- [ ] Test guide with member of Admin team

### Resources
- Admin team member currently performing function: Bonnie Wolfe

#### How to make a guide
- [Template for creating guides - WIP](https://docs.google.com/document/d/1-8gmeC-wnfM8C8fVvmTP1BLA2WfNjKH_XJrHB1OAV6Q/edit)
 - [UI/UX for Guides](https://github.com/hackforla/knowledgebase-content/issues/93)

#### Folders
- Recordings & Transcripts
   - 📁[Recordings general folder](https://drive.google.com/drive/folders/1dmX5df5TXm8F209O4-_BRmuW0NIcT-Ss)
   - 📁[Add Owners to the 1Password Account ](https://drive.google.com/drive/folders/1dXJwdKCxB75lelSvlZ7bh0bJLG2BPtYu)
   - Link to specific recording and transcript (add links to the emojis)
      - ⏺️
      - ✏️
- Guides
  - [Guides general folder](https://drive.google.com/drive/folders/13aT7T3HblNidcwm2CMy7LQg-mAULL3Q7)
   - Add Owners to the 1Password Account
   - [📁](https://drive.google.com/drive/folders/10FTRqoWU6_fGenP7fDfydDHVv8-l2jy3)
   - [👷‍♀️](https://docs.google.com/document/d/1_70xO4Qv9s3yj5V343OD5Zksqfngc-hTpVpvDzQNxt8/edit)

#### Legend
📁 = Folder
✏️= Transcription
⏺️ = Recording
📝 = "As-Is":  Transcript edited down to steps (no pictures, no focus on writing instructions for others)
👷‍♀️ = Draft Guide Take the write up, put it in the Guide template and screen shots (or notes that screen shots are needed) and start working on the language.
🎉= Completed Guide

#### Location of draft guide.
- Epic Issue hackforla/knowledgebase-content#132 
- 👷‍♀️ [Add Owners to the 1Password Account](https://docs.google.com/document/d/1_70xO4Qv9s3yj5V343OD5Zksqfngc-hTpVpvDzQNxt8/edit)

**Comment by kcoronel** [comment]
@ExperimentsInHonesty need to record this workflow with you and/or take screenshots with you.

**Comment by kcoronel** [comment]
This draft is ready for review :)
