### ISSUE TITLE
Define Automations for the Org repos

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/admin#52]
### Overview
We need to define what repo automations Admin need so that we can create a series of issues in the engineering CoP that will lead to the organization having more standardized methods and tools across repos

### Action Items
- [ ] Brainstorm ideas
- [ ] Create Spreadsheet
- [ ] Prioritize
- [ ] Gather more info on the ideas that are Must Haves

### Resources/Instructions

```
### Proposal Overview

### Resources

### Priority
- [ ] Must Have
- [ ] Should Have
- [ ] Could Have
- [ ] Won't Have this time
```

**Comment by ExperimentsInHonesty** [comment]
### Dependency
- Soft dependency: If we had the GHA to automate adding of project name label to each repo then we could create Special Purpose Repos and fill them faster.

### Management of Projects
We need to be able to see all the project's outstanding items in one place

### Proposal Overview
Create an - [An Org wide project board (at org level) to unify all the outstanding task items for projects](https://github.com/orgs/hackforla/projects/20/views/1) and have that board share issues with Special purpose repositories so that project have a place to see what their outstanding project maintenance and new tool integration.

#### Detail about Special Purpose Repositories
Will have labels for project name  (e.g., `project name: BallotNav`, `project name: Home Unite Us`) and a label that unifies all the issues in the special purpose repo (e.g., the Drive Migration repo has a label called feature: `Google Drive Migration`)
Drive migration audit: https://github.com/hackforla/google-drive-migration/issues

### Resources


### Priority
- [ ] Must Have
- [x] Should Have
- [ ] Could Have
- [ ] Won't Have this time

**Comment by ExperimentsInHonesty** [comment]
### Proposal Overview
Create an automation that allows for installing specific labels onto a repo or group of repos as defined by a text file so that we can easily roll out a new label structure to teams

### Resources
GitHub API info for creating labels https://docs.github.com/en/rest/issues/labels
A person's automation for adding labels to a repo: https://gist.github.com/liuderchi/8d1c8e0a74fd690523288acedd163682

### Priority
- [ ] Must Have
- [ ] Should Have
- [ ] Could Have
- [ ] Won't Have this time

**Comment by ExperimentsInHonesty** [comment]
# Brainstorming

### creates a new issue each week on a specified date
- uses
   - Agendas
    - Weekly label check

### Creates a series of labels (one for each project) on a specific repo
- details
  - has a configuration file where you can specify
     - name of label
     - list of project names
- uses
  - applying labels to issues for all projects
    - Google Drive Migration
    - Gmail email filter
 
### Creates a series of issues (one for each project) from a single template
- details
  - has a configuration file where you can specify
     - template issue
     - list of project names
     - label pattern to apply (project name: *.*) - uses labels created by `Creates a series of labels (one for each project) on a specific repo`

### Visualizing milestone progress and specifically current quarter progress

**Comment by ExperimentsInHonesty** [comment]
# Brainstorming with some useful research on specific possible automation or linter.
### Link checker which will run weekly and check incoming PRs
#### Resources/Instructions
- Browser based XML Sitemap creator: https://www.xml-sitemaps.com/
   - [Results of checking for pages 2022-10-18](https://www.xml-sitemaps.com/details-merlcenter.org-be5d57a42.html)
- Web based link checker 1: https://error404.atomseo.com (checks all the pages at once)
   - [Raw results of link checking 2022-10-18](https://error404.atomseo.com/SeoCheck/Report/merlcenter.org/2022-10-18/free)
      - efficacy:  
         - accuracy: stated that there were 14 errors.  Caught 6 of 9 real errors
         - time: very fast, because its all in one place, but it can't be downloaded or copied, so any time you save, is eaten up when you have to document the links and the page they come from.   
- Browser based link checker 2: [Chrome Extension: website broken link and 404 error checker](https://chrome.google.com/webstore/detail/website-broken-link-and-4/kkjfobdnekhdpmgomkpeibhlnmcjgian/related?hl=en-GB) - checks the pages 1-by-1 but lets you download the results of each page analysis in csv.  Was more accurate than checker 1.
    - efficacy:  
       - accuracy: accuracy: stated that there were a lot of errors and unverified links (I didn't keep track of how many).  Caught 9 of 9 real errors  
       - time: very time consuming, as each page must be checked, then spreadsheet downloaded, then filtered by error, before the URL can be checked.
- Web based checker 3: http://www.brokenlinkcheck.com/ - checks the whole website
    - efficacy:  
       - accuracy: Caught 9 of 9 real errors  
       - time: was fast and the contents easy to read, but results not downloadable, a lot of  manual cutting and pasting required.
- Web based checker 4: https://www.deadlinkchecker.com/ - checks whole site
    - efficacy:  
       - accuracy: Caught 7 of 9 real errors , also caught errors in code (resources that are referenced in the CSS but don't actually appear in the repo)
       - time: was fast and the contents easy to download direct to a spreadsheet

#### Analysis and Recommendations
- If you have to use a post publication broken link checker, use Checker 4  to find the list of links you should check.  Once you have fixed your links then you can use Checker 2 to catch the remaining broken links (if any)
