### ISSUE TITLE
Contractor: Invoice Requirements

### ISSUE THREAD

**Issue by Rabia2219** [hackforla/admin#69]

**Comment by Rabia2219** [comment]
### Overview
I need to invoice every week, so I can keep my employment

### Action Items
####  Setup invoice doc
- [ ] Copy invoice document from template by going to resource 1.01 and choosing the `USE TEMPLATE` button
- Customize invoice doc 
  - [ ] Name of document: `AudreyChurch[Replace INVOICE NUMBER]CalendaringInvoice`
  - [ ] Your name
  - [ ] Address
  - [ ] Phone
  - [ ] Email
- [ ] create a link to the customized invoice document by revising the URL.  Replace `edit` (and everything that comes after it)  with `template/preview` and then add that link to resource 2.01
- [ ] Move the document into a folder where you will keep invoices and related documents

####  Setup spreadsheet
- [ ] Copy spreadsheet from template (resource 1.02)
- Customize invoice doc 
  - [ ] Name of document: `Audrey CTS Calendaring Time card template`
- [ ] add the link to your new spreadsheet to resource 2.02

#### Task each week
- [ ] Copy these instructions each week to a new comment and then do the steps
```
Period: YYYY-MM-DD to MM-DD
### Record Hours
- [ ] Go to spreadsheet (resource 2.02)
- [ ] Duplicate the spreadsheet template tab called `Template: Period YYYY-MM-DD to MM-DD` by right clicking on it and then choosing duplicate
- [ ] record hours each day
- [ ] add brief notes to the work done summary

### Create New Invoice
- [ ] copy the invoice template document you customized (resource 2.01)
- [ ] name the new invoice document by replacing the `[Replace INVOICE NUMBER]` inside the title `AudreyChurch[Replace INVOICE NUMBER]CalendaringInvoice` by using this format using this format YYYYMMDD-NN (e.g. 20230215-01)
- [ ] Go to spreadsheet
   - [ ] change name to current billing period (e.g., Period 2024-02-13 to 02-19)
   - [ ] delete blank rows
   - [ ] copy columns A though D
- [ ] Go to the new invoice you created 
   - [ ] paste table where indicated
      - [ ] Choose paste unlinked>paste
   - [ ] Right-click on the table, choose Table properties
      - [ ] in right format pane, choose Alignment>Table Alignment: Center
   - [ ] summarize the work from your notes in the spreadsheet and add to the document as bullets
   - [ ] replace the [Replace DATE] with the date you create/submit the invoice on 
   - [ ] replace the [Replace INVOICE#] using this format YYYYMMDD-NN (e.g. 20230215-01)
   - [ ] once the invoice is finalized, move it to your invoice folder (resource 1.00)

### Submit Invoice
- [ ] save the invoice you just created as a pdf
- [ ] upload the pdf to your invoice folder (resource 1.00)
- [ ] compose a new email with the subject line: `CTS: Audrey Invoice`
- [ ] link the Google Doc invoice and .pdf
- [ ] send email to: `team@civictechstructure.org`

### Congrats! your done!! 
- [ ] Hide this comment as Resolved
```

### Resources/Instructions
#### Folders
- 1.00 [CTS, Invoices from Audrey](https://drive.google.com/drive/folders/1ADDYjDmvCn_iju4kSEgMM7raOKyZYJuo?usp=share_link)

#### Guides
- [How to save a Google doc as a pdf](https://www.businessinsider.com/guides/tech/how-to-save-a-google-doc-as-a-pdf)
- [How to upload a file to Google drive](https://www.techrepublic.com/article/how-to-upload-a-file-to-google-drive/)

#### Invoice period and deadlines
- Invoice period will be Monday-Sunday
- Invoices need to be submitted on Sunday by midnight PST
- Invoices swill be paid on the Saturday following.

#### Templates to start with the first time
- 1.01 [New Invoice](https://docs.google.com/document/d/1_Hw072S_gSQc3kD3eYu3ousBDWJGN4eeJa_BtY8ErRo/template/preview)
- 1.02 [Project Timesheet](https://docs.google.com/spreadsheets/d/1YGoJ3bwUCnG_G_z9qKW5nZTfzmqMPwobxUn7OabsgXk/template/preview)

#### Templates customized by Audrey
- 2.01 [Audrey's invoice template for CTS]
- 2.02 [Audrey's spreadsheet]

**Comment by Rabia2219** [comment]
Period: YYYY-MM-DD to MM-DD
### Record Hours
- [ ] Go to spreadsheet (resource 2.02)
- [ ] Duplicate the spreadsheet template tab called `Template: Period YYYY-MM-DD to MM-DD` by right clicking on it and then choosing duplicate
- [ ] record hours each day
- [ ] add brief notes to the work done summary

### Create New Invoice
- [ ] copy the invoice template document you customized (resource 2.01)
- [ ] name the new invoice document by replacing the `[Replace INVOICE NUMBER]` inside the title `AudreyChurch[Replace INVOICE NUMBER]CalendaringInvoice` by using this format using this format YYYYMMDD-NN (e.g. 20230215-01)
- [ ] Go to spreadsheet
   - [ ] change name to current billing period (e.g., Period 2024-02-13 to 02-19)
   - [ ] delete blank rows
   - [ ] copy columns A though D
- [ ] Go to the new invoice you created 
   - [ ] paste table where indicated
      - [ ] Choose paste unlinked>paste
   - [ ] Right-click on the table, choose Table properties
      - [ ] in right format pane, choose Alignment>Table Alignment: Center
   - [ ] summarize the work from your notes in the spreadsheet and add to the document as bullets
   - [ ] replace the [Replace DATE] with the date you create/submit the invoice on 
   - [ ] replace the [Replace INVOICE#] using this format YYYYMMDD-NN (e.g. 20230215-01)
   - [ ] once the invoice is finalized, move it to your invoice folder (resource 1.00)

### Submit Invoice
- [ ] save the invoice you just created as a pdf
- [ ] upload the pdf to your invoice folder (resource 1.00)
- [ ] compose a new email with the subject line: `CTS: Audrey Invoice`
- [ ] link the Google Doc invoice and .pdf
- [ ] send email to: `team@civictechstructure.org`

### Congrats! your done!! 
- [ ] Hide this comment as Resolved

**Comment by Rabia2219** [comment]
### Savvy time 
https://savvytime.com/converter/spain-madrid-to-pst-cst
