### ISSUE TITLE
2024 Meetup set up

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/admin#79]
### Overview
We need to set up all the meetups for 2024 including the zoom webinar links

#### Setup Spreadsheet
- [x] Create a new tab on the spreadsheet for 2024
#### Choose dates
- [x] Print out calendar from Jan 2024-Jan 2025
   - [x] Add federal holidays 
   - [x] Add religious work off dates
   - [x] Add July and December off
   - [x] add any personal travel days off
- [x] Choose dates
#### Setup Meetup
- [x] fix the dates in meetup so that they match the chosen dates
- [x] Add the meetup URLs to spreadsheet
- [x] update the content in the meetup if we have changed it.
#### Setup Zoom Webinars
- [x] Setup links in zoom4 for the Webinars
- [x] Add webinar registration link to spreadsheet
#### Setup Zoom Onboarding part 2
- [x] Setup links in Zoom 2 and use Zoom only if necessary for the Monday meetings. See notes below.
- [x] Add Zoom link to spreadsheet 
- [x] Add email addresses for host Zoom to spreadsheet
#### Update Meetup
- [x] add the link for the zoom to each meetup invite to its location
- [x] Customize the text `Zoom` to link to the zoom registration link
#### Update the Onboarding Zoom Item in 1Password
- [x] Add the meeting registration links (webinar and part 2) for onboarding for all dates
- [ ] Potentially, add the webinar passcode
#### Create Calendar invites
- [x] Create a mail merge using the spreadsheet and a document
   - [x] Add content from comments below
   - [x] Update End Note in spreadsheet
   - [x] create the mail merge document
   - [x] Add document to links below
- [x] repeat steps for Part 2
- [x] Create the dates for Part 1 in hfla-email-all@
    - [x] Create a non-recurring event for the first date
    - [x] Add details in the description for that day from the mail merge document (these steps are necessary to fix the spacing create by the mail merge)
       - [x] copy the message from the mail merge document
       - [x] paste it in an empty Slack message
       - [x] copy the message from Slack
       - [x] paste it in the invite description
    - [x] duplicate the event for each consecutive date and customize the invite for each using the same process above
    - [x] repeat steps for the invite for Part 2
#### Panelists
- [ ] Find out who will be a panelist
- [ ] Add panelists via the .csv to the invites

### Resources/Instructions
- Spreadsheet: [Onboarding: Meetup URLs and Brigade Zoom Webinar URLs](https://docs.google.com/spreadsheets/d/1RyczF7G8a-MIJECb3CWzjnBRuYdHpee9PLzUYJpqjPc/edit#gid=0)
- [Printable calendar 2024](https://print-a-calendar.com/printable-calendars/2024/one-page-per-month)
- Holidays
  - [Federal Holidays 2024](https://www.opm.gov/policy-data-oversight/pay-leave/federal-holidays/#url=2024)
  - [Multi faith observances](https://www.xavier.edu/jesuitresource/online-resources/calendar-religious-holidays-and-observances/multi-faith-calendar---next-year) - includes work restricted)
- Meetup: https://www.meetup.com/hackforla/events/
- [Panelist list](https://docs.google.com/spreadsheets/d/1WT9ykFvpDv-P9ghyZ8YJ_V2CBBo3GqA3G5pK4t5a-uw/edit#gid=0)
- [Onboarding: Calendar Invites - Part 1](https://docs.google.com/document/d/11AaLOhvqtF3AXwu5PjsuDRjWPjm3KUuYritsu0TjC6g/edit)
- [Onboarding: Calendar Invites - Part 2](https://docs.google.com/document/d/1WF5adign2s2B8pkt2MH-kFE7N_rx-Ce7I1xHZ_f0cTc/edit)
- [Mail merge of Onboarding: Calendar Invites - Part 1](https://docs.google.com/document/d/18Dv-wzrhvSb5-G4945JCWlZ4iWlwHHaXjZMi-zhNrRE/edit)
- [Mail merge of Onboarding: Calendar Invites - Part 2](https://docs.google.com/document/d/1dioPuq9WO5rthtQIcI6kqhw-nWgknBzW9s9ibnEbF4Q/edit)

#### Notes
- The reason we used zoom@ on Mondays, is that there was a conflict with Food Oasis.

**Comment by ExperimentsInHonesty** [comment]
# Part 2
[REPLACE with Zoom account email]

You are on this calendar invite because you have been added as a co-host and representative of your CoP or project to the onboarding.  If you cannot attend this instance or want to be removed permanently, please write to #admin channel and we will offboard you from the resources.

[REPLACE with Zoom link to part 2]

Sign into the meeting, use the 'Reactions' menu at the bottom of the screen to 'raise your hand'. This will let the host know that you need to be made a co-host.

Info related to onboarding can be found: 
Meetup: [REPLACE with link to meetup]
WIKI: https://github.com/hackforla/admin/wiki/Onboarding-Events
1Password vault: HfLA Onboarding - panelists (all the links we are trying to keep private)

[REPLACE with End Note]

---
~Add this to the last one in nov
Note: This is the last onboarding for the year. We will schedule the 2025 onboardings in December.~


---
~Add this to the last one in june
Note: This is the last onboarding until August.~

**Comment by ExperimentsInHonesty** [comment]
# Part 1
You are on this calendar invite because you have been added as a panelist to the onboarding.  If you do not want to be a panelist anymore, please write to #admin channel and we will offboard you from all the resources.

The zoom login for the webinar should be in your email (it comes direct from zoom).  Search for it using the text "Panelist for Hack for LA Onboarding"  If you don't have it, write to us on the #admin Slack channel.

You can also log in using CTS: Zoom4 (credentials in the 1Password vault: Zoom)

Info related to onboarding can be found: 
Meetup: [REPLACE with link to meetup]
WIKI: https://github.com/hackforla/admin/wiki/Onboarding-Events
1Password vault: HfLA Onboarding - panelists (all the links we are trying to keep private)

~Note: it says weekly on Monday and Tuesday, but it's actually for the following dates only:
2024-01-02	Tuesday
2024-01-16	Tuesday
2024-02-05	Monday
2024-02-20	Tuesday
2024-03-04	Monday
2024-03-26	Tuesday
2024-04-08	Monday
2024-04-23	Tuesday
2024-05-06	Monday
2024-05-21	Tuesday
2024-06-03	Monday
2024-06-18	Tuesday
2024-08-05	Monday
2024-08-20	Tuesday
2024-09-09	Monday
2024-09-24	Tuesday
2024-10-07	Monday
2024-10-22	Tuesday
2024-11-04	Monday
2024-11-19	Tuesday~

**Comment by ExperimentsInHonesty** [comment]
This issue takes 12 hours of labor to accomplish
it requires that you to
- be co-organizer on meetup
- have access to 1password vault for Onboarding - admin and Onboarding - panelist

**Comment by Rabia2219** [comment]
#### Notes
- added Email column to spreadsheet so that we didn't have to manually change it for Monday/Tuesday
- Added End Note column to spreadsheet so that we don't have to manually add it to the corresponding invite(s). Will need to update for every year
- Had to use Slack to adjust spacing created by Mail Merge
- Mail Merge documents have the invites for January 2025 but I did not create them on the calendar
- Need to review the most efficient way to create calendar invites in this particular case

**Comment by kcoronel** [comment]
can we close this issue @Rabia2219 @ExperimentsInHonesty
